### ISSUE TITLE
Изисквания 

### ISSUE THREAD

**Issue by BorislavKrumov** [BorislavKrumov/WhatYouKnowIOS#1]
Задължителни изисквания:
- [x] Прилагане на MVC или друг design pattern (VIPER, MVVM и други)
- [x] Използване на Interface Builder (Storyboard)
- [x] Използване на Swift
- [x] Правилна употреба на access controls

Избираеми изисквания:
- [x] Минимум 3 екрана, свързани един с друг
- [ ] Употреба на UINavigationController
- [ ] Употреба на UITabViewController
- [ ] Употреба на UISplitViewController
- [x] Употреба на Modal Screen Presentation
- [ ] Употреба на UITableView или UICollectionView
- [x] #7 Употреба на поне една анимация 
- [x] Употреба на custom protocol/delegation
- [x] #6 Използване на persistance-Core Data
- [x] Създаване на Custom View
- [x] Създаване на поне един Extension
- [x] #8 Използване на enum
- [x] Използване на struct
- [x] #9 Използване на поне един gesture в логиката на приложението
- [x] Употреба на поне един closure (в high-order функция, custom closure или async логика)
- [ ] Употреба на Multithreading механизм
- [x] Употреба на UIScrollView
- [x] Извличане на данни от сървър (networking)
- [x] Използване на UIStackView
- [ ] Custom / Convenience Init
- [x] Употреба на Singleton pattern (edited)

**Comment by BorislavKrumov** [comment]
Избираемите са общо 21, като трябва да използват/изберат поне 15.

**Comment by BorislavKrumov** [comment]
Приложението е оформено за iPhone 13 Pro
